//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakunaMatata_Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public int MachitietPN { get; set; }
        public Nullable<int> MaPN { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<decimal> Dongianhap { get; set; }
        public Nullable<int> Soluongnhap { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
